-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Experiment CASCADE;
DROP TABLE IF EXISTS LabUser CASCADE;
DROP TABLE IF EXISTS Laboratory CASCADE;
DROP TABLE IF EXISTS TimeSlot CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS SubjectInfo CASCADE;
DROP TABLE IF EXISTS RequiredInfo CASCADE;
DROP TABLE IF EXISTS AcceptableResponse CASCADE;
DROP TABLE IF EXISTS UserExperiment CASCADE;
